### ISSUE TITLE
All contributions welcome 😊 

### ISSUE THREAD

**Issue by chartgerink** [libscie/libscie.org#4]
This is a thread to add contributors under the [all-contributors specs](https://allcontributors.org/docs/en/emoji-key) 🥳

**Comment by chartgerink** [comment]
@all-contributors add @psobrakseaton for design and thinking

**Comment by chartgerink** [comment]
@all-contributors add @chartgerink for maintenance and code and infrastructure

**Comment by chartgerink** [comment]
@nsunami would you be open to checking out the website and sharing some of your thoughts? We [softlaunched the new website](https://libscie.org) and I'd very much appreciate any feedback ☺️

**Comment by nsunami** [comment]
Of course! 

Here are my initial thoughts:

1. When I open the page, the background flashes to white and back to black. Is there a way to fix it so that the page renders black? (maybe it's set by OS's dark mode setting?)
2. The title banner on the top looked like a search bar to me. It's probably because of the borders. What if we make the whole box filled with deep purple color? I think the white text will still pop there. The width of the banner works for me since they are aligned with the contents that follow.
3. This is just an idea but, can the "Tell us your challenge" banner be filled with color, rather than black? Also I wasn't sure what happens when I click the "->" button.
4. I loved the big title and the message. 
5. I also liked the flowing strings graphics behind the title. For a sense of closure, how about placing a similar background graphic in the footer?
6. I really liked the icons! A small point---is there a way to make icons represent the items? For example, would it work if you put a black podcast icon on top of the gem?
7. Beautiful color scheme/palette throughout!

**Comment by chartgerink** [comment]
Thanks @nsunami ☺️ 

1. Good point - I opened #20 to document this and continue the discussion.
2. Interesting! Does that still look like that with more navigation buttons (forthcoming when the other pages are added)?
<img width="995" alt="Screenshot 2021-06-17 at 10 32 47" src="https://user-images.githubusercontent.com/2946344/122361347-7495a280-cf57-11eb-81c5-a3d143af47d4.png">
3. Definitely can be - @psobrakseaton had this as a design option and found it intense. The button feedback is valuable too, much appreciated.
4. 😊 
5. @psobrakseaton you care to weigh in? This is an interesting suggestion we didn't consider before.
6. Will ask @psobrakseaton as well - he is the designer and can weigh in
7. 😊 

@all-contributors add @nsunami for ideas
